### ISSUE TITLE
Unable to import qmateservice at spec level

### ISSUE THREAD

**Issue by RAMA-KONATAM** [SAP/wdio-qmate-service#147]
**Describe the bug**
I have installed the Qmate service as per the Qmate documentation. But I am unable to import or use the (await ui5.navigation) command. All the commands are showing as errors. There is no information on how to import Qmate service at the spec level.

**To Reproduce**
1. Install Qmate service for the WDIO project
2. Add the service in the WDIO conf file
3. Use the Qmate commands like (ui5.navigation)
4. Mouse hover on the (await ui5.navigation) and see the error --- **Can not find name ui5**

**Expected behavior**
Qmate service should work without errors
**Executable code snippet**

**Screenshots**
<img width="915" alt="Screenshot 2023-05-04 at 7 26 52 PM" src="https://user-images.githubusercontent.com/107562271/236230100-aac9e64a-10f5-4367-b72e-f8bee23b1ab7.png">

**System information:**
 - OS: Mac
 - Chrome - Version 112.0.5615.137
 - Qmate Version - latest

**Comment by DIFSRIP** [comment]
Hi @RAMA-KONATAM,

sorry for the late reply. Normally issues are not tracked via this repo, hence I missed it.

you have to install the related types to enable intelisense and avoid type issues.
https://pages.github.tools.sap/sProcurement/qmate/sections/setup/intelliSense/

Is there an actual execution error as well? Or just the errors in the IDE?

**Comment by Templada** [comment]
Hi @RAMA-KONATAM,

i will close the issue for now. If it still persists please re-open.

Best regards,
Marvin
