### ISSUE TITLE
[BUG][LOW] - I am unable to run qmates locally in vs code.

### ISSUE THREAD

**Issue by LakshmiSM-sap** [SAP/wdio-qmate-service#304]
**Describe the issue**
A clear and concise description of the bug.

I am facing below error when trying to run qmate script. 
![image](https://github.com/user-attachments/assets/74565fb9-3bb7-4f98-aa7b-3cab7a792e91)

When trying to run - npm init wdio@latest 
![image](https://github.com/user-attachments/assets/9b7503ce-6c9f-4004-a034-e7152f59ec98)

When I am trying to follow setup steps given here - https://sap.github.io/wdio-qmate-service/sections/gettingStarted/setup/
and install node js- 
# installs fnm (Fast Node Manager)
winget install Schniz.fnm
# configure fnm environment
fnm env --use-on-cd | Out-String | Invoke-Expression

and run above prompts I am getting error like fnm is not recognised. 

**Error message / console output**
All relevant console outputs including the error message(s).
Attached the screenshots 

**Steps to reproduce**

**Executable code snippet**

*config.js*
```js title="config"
const path = require("path");
const merge = require(path.resolve(process.env.DEEPMERGE_PATH));
const profile = require(path.resolve(process.env.QMATE_CONFIGS, "chrome.conf.js"));

exports.config = merge(profile.config, {
  baseUrl: "<your_system_url>",

  specs: [
    path.resolve(__dirname, "<your_spec_path>")
  ]
});
```

*yourtest.spec.js*
```js
describe("01_yourScript - describe the test", function () {

    it("Step 01: describe the step", async function () {
        // [...]
    });

    it("Step 02: describe the step", async function () {
        // [...]
    });

    // [...]
    
});
```

**Expected behavior**
A clear and concise description of the expected behavior.

**Screenshots**
If applicable, add screenshots to help describing the issue.

**System information:**
 - OS: [e.g. Windows, Mac, Linux]
 - Browser [e.g. Chrome - Version 96.0.4664.93]
 - Qmate Service Version [e.g. 1.0.1]

**Additional comments**
Any other relevant infromation about the issue.

**Comment by Templada** [comment]
Hi @LakshmiSM-sap ,

first at all, do not put any internal information on a public github repository.
Even if it is from SAP!

Secondly, I see that you are having cloned your repository into a OneDrive folder, which is not good!

At third we can not take responsibility for node installation/package- manager.

This is your very own setup, and therefore closing the issue as it has nothing to with qmate or qmate-service itself.

Hope you understand.

Best Regards,
Marvin
